branches:
  only:
  - master
language: php
php:
- '5.5'
- '5.6'
- '7.0'
- '7.1'
env:
  global:
  - setup=basic
matrix:
  include:
  - php: 5.5
    env: setup=lowest
  - php: 7.0
    env: setup=stable
sudo: false
addons:
  code_climate:
    repo_token: $cc_token
before_install:
- travis_retry composer self-update
install:
- if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist;
  fi
- if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction
  --prefer-stable; fi
- if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction
  --prefer-lowest --prefer-stable; fi
script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
after_success:
- vendor/bin/test-reporter
