language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.6
      env: setup=lowest
    - php: 7.0
      env: setup=stable


sudo: false

addons:
  code_climate:
    repo_token: 9ae306657e37eb2e94d1a8ee82d0993b819f75d48c35d6b0b949c56bb02964a7

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text

after_success:
  - vendor/bin/test-reporter